import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const futura = localFont({
  src: [
    {
      path: "./fonts/FuturaStdLight.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/FuturaStdMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/FuturaStdBook.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/FuturaStdHeavy.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/FuturaStdBold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/FuturaStdExtraBold.otf",
      weight: "900",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={futura.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
